# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: envd-server
    main: ./cmd/envd-server
    binary: envd-server
    ldflags:
      - -s -w
      - -X github.com/tensorchord/envd-server/pkg/version.version={{ .Version }}
      - -X github.com/tensorchord/envd-server/pkg/version.buildDate={{ .Date }}
      - -X github.com/tensorchord/envd-server/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/tensorchord/envd-server/pkg/version.gitTreeState=clean
      - -X github.com/tensorchord/envd-server/pkg/version.gitTag={{ .Tag }}
archives:
  - id: envd-server
    format: binary
    builds:
      - envd-server
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
- image_templates:
  - "tensorchord/envd-server:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  ids:
  - envd-server
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "tensorchord/envd-server:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  ids:
  - envd-server
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: tensorchord/envd-server:{{ .Version }}
  image_templates:
  - tensorchord/envd-server:{{ .Version }}-amd64
  - tensorchord/envd-server:{{ .Version }}-arm64v8
