// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EnvDataTable: typeof import('./components/EnvDataTable.vue')['default']
    IMaterialSymbolsCalendarMonth: typeof import('~icons/material-symbols/calendar-month')['default']
    IMaterialSymbolsInsertChartRounded: typeof import('~icons/material-symbols/insert-chart-rounded')['default']
    IMdiBin: typeof import('~icons/mdi/bin')['default']
    IMdiDriveDocument: typeof import('~icons/mdi/drive-document')['default']
    IMdiGear: typeof import('~icons/mdi/gear')['default']
    LoginImg: typeof import('./components/LoginImg.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
