// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiAccountCircleOutline: typeof import('~icons/mdi/account-circle-outline')['default']
    InfoModal: typeof import('./components/InfoModal.vue')['default']
    LoginImg: typeof import('./components/LoginImg.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
  }
}
