apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envd-server.fullname" . }}
  labels:
    {{- include "envd-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "envd-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "envd-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "envd-server.serviceAccountName" . }}
      serviceAccountName: {{ include "envd-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - configMap:
            name: {{ include "envd-server.fullname" . }}
          name: config
        - secret:
            secretName: {{ include "envd-server.fullname" . }}
            defaultMode: 0666
          name: secret
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /envd-server
            - --hostkey
            - /etc/containerssh/hostkey
          ports:
            - name: envdserver
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /v1
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /v1
          #     port: http
          volumeMounts:
            - mountPath: /etc/containerssh/hostkey
              name: secret
              subPath: hostkey
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: containerssh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.containersshimage.repository }}:{{ .Values.containersshimage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.containersshimage.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/containerssh/config.yaml
            name: config
            subPath: config.yaml
          - mountPath: /etc/containerssh/hostkey
            name: secret
            subPath: hostkey
          - mountPath: /etc/containerssh/privatekey
            name: secret
            subPath: privatekey
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
