apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "envd-server.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/logs
  - pods/exec
  - services
  verbs:
  - '*'
