apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envd-server.fullname" . }}
  labels:
    {{- include "envd-server.labels" . | nindent 4 }}
type: Opaque
data:
  privatekey: |-
    {{ .Files.Get "secretkeys/backend_pod" | b64enc }}
  publickey: |-
    {{ .Files.Get "secretkeys/backend_pod.pub" | b64enc }}
  hostkey: |-
    {{ .Files.Get "secretkeys/hostkey" | b64enc }}
