apiVersion: v1
kind: Service
metadata:
  name: {{ include "envd-server.fullname" . }}
  labels:
    {{- include "envd-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serverPort }}
      targetPort: envdserver
      protocol: TCP
      name: envd-server
      nodePort: {{ .Values.service.serverNodePort }}
    - port: {{ .Values.service.containersshPort }}
      targetPort: ssh
      protocol: TCP
      name: ssh
      nodePort: {{ .Values.service.containersshNodePort }}
  selector:
    {{- include "envd-server.selectorLabels" . | nindent 4 }}
