// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package query

import (
	"github.com/jackc/pgtype"
)

type ImageInfo struct {
	ID         int64        `json:"id"`
	OwnerToken string       `json:"owner_token"`
	Name       string       `json:"name"`
	Digest     string       `json:"digest"`
	Created    int64        `json:"created"`
	Size       int64        `json:"size"`
	Labels     pgtype.JSONB `json:"labels"`
}

type User struct {
	ID            int64  `json:"id"`
	IdentityToken string `json:"identity_token"`
	PublicKey     []byte `json:"public_key"`
}
