// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package query

import ()

type User struct {
	ID            int64  `json:"id"`
	IdentityToken string `json:"identity_token"`
	PublicKey     []byte `json:"public_key"`
}
