// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package query

import (
	"context"
)

type Querier interface {
	CreateImageInfo(ctx context.Context, arg CreateImageInfoParams) (ImageInfo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetImageInfo(ctx context.Context, arg GetImageInfoParams) (ImageInfo, error)
	GetUser(ctx context.Context, identityToken string) (User, error)
	ListImageByOwner(ctx context.Context, ownerToken string) ([]ImageInfo, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
