// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package query

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  login_name, password_hash, public_key
) VALUES (
  $1, $2, $3
)
RETURNING login_name, public_key
`

type CreateUserParams struct {
	LoginName    string `json:"login_name"`
	PasswordHash string `json:"password_hash"`
	PublicKey    []byte `json:"public_key"`
}

type CreateUserRow struct {
	LoginName string `json:"login_name"`
	PublicKey []byte `json:"public_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.LoginName, arg.PasswordHash, arg.PublicKey)
	var i CreateUserRow
	err := row.Scan(&i.LoginName, &i.PublicKey)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, public_key, login_name, password_hash FROM users
WHERE login_name = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, loginName string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, loginName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.LoginName,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, public_key, login_name, password_hash FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.LoginName,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
